export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'; 
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'; 
export const ITEM_LIST_ERROR = 'ITEM_LIST_ERROR';

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST'; 
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS'; 
export const ITEM_DETAILS_ERROR = 'ITEM_DETAILS_ERROR';